name: 'Bridgecrew Github Action'
author: 'Bridgecrew.io'
description: 'Find and fix security and compliance issues in infrastructure code using Bridgecrew Action'
inputs:
  directory:
    description: 'directory with infrastructure code to scan'
    default: '.'
    required: false
  check:
    description: 'Run scan only on a specific check identifier (comma separated)'
    required: false
  skip_check:
    description: 'Run scan on all checks but a specific check identifier (comma separated)'
    required: false
  quiet:
    description: 'display only failed checks'
    required: false
  api-key:
    description: 'Environment variable name of the Bridgecrew API key from Bridgecrew app'
    required: false
  soft_fail:
    description: 'Runs checks but suppresses error code'
    required: false
  external_checks_dir:
    description: 'Directory for custom checks to be loaded'
    required: false
  output_format:
    description: 'Output Format (cli, cli+sarif, json, junitxml)'
    required: false
    default: 'sarif'
  log_level:
    description: 'The logging level for the CLI'
    required: false
  download_external_modules:
    description: 'Whether to download modules from external sources (e.g., other repos or the registry). Defaults to false.'
    required: false
  config_file:
    description: 'bridgecrew configuration file'
    required: false

branding:
  icon: 'shield'
  color: 'purple'

runs:
  using: 'docker'
  image: 'docker://bridgecrew/bridgecrew:2.0.777'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.check }}
    - ${{ inputs.skip_check }}
    - ${{ inputs.quiet }}
    - ${{ inputs.soft_fail }}
    - ${{ inputs.external_checks_dir }}
    - ${{ inputs.output_format }}
    - ${{ inputs.log_level }}
    - ${{ inputs.download_external_modules }}
    - ${{ inputs.config_file }}

  env:
    API_KEY_VARIABLE: ${{ inputs.api-key }}
